services:
  - type: web
    name: figma-to-vtexio
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    buildDir: build